name: Build and Release APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Create APK directory
      run: mkdir -p beta-release

    - name: Move APK to beta-release
      run: mv app/build/outputs/apk/release/app-release.apk beta-release/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: beta-release/
